const canvas=document.getElementById("gameCanvas"),ctx=canvas.getContext("2d");
const W=canvas.width,H=canvas.height,saveKey="idle_arpg_v3";
let currentMap=GAME_DATA.maps[0];
const state={player:{x:W/2,y:H/2,hp:100,maxHp:100,damage:10,level:1,xp:0,xpNeeded:100,frame:0},gold:0,kills:0,enemies:[],spawnTimer:0,attackTimer:0,inventory:[],equipped:{weapon:null,armor:null,ring:null,boots:null},last:performance.now()};
const cache={};
function img(path){if(!cache[path]){const i=new Image();i.src=path;cache[path]=i}return cache[path]}
function pickFrame(list, every=120){if(!list.length)return null;return list[Math.floor(performance.now()/every)%list.length]}
function log(m){const e=document.getElementById("log");e.innerHTML="<div>"+m+"</div>"+e.innerHTML}
function persist(){try{localStorage.setItem(saveKey,JSON.stringify({...state,enemies:[],currentMapId:currentMap.id}))}catch(e){}}
function restore(){try{const r=localStorage.getItem(saveKey);if(!r)return;const s=JSON.parse(r);Object.assign(state,s);Object.assign(state.player,s.player||{});Object.assign(state.equipped,s.equipped||{});currentMap=GAME_DATA.maps.find(m=>m.id===s.currentMapId)||GAME_DATA.maps[0]}catch(e){}}
function spawnEnemy(){const b=GAME_DATA.monster,a=Math.random()*Math.PI*2,d=240+Math.random()*190;let x=state.player.x+Math.cos(a)*d,y=state.player.y+Math.sin(a)*d;x=Math.max(50,Math.min(W-50,x));y=Math.max(90,Math.min(H-50,y));const scale=1+(state.player.level-1)*.08;state.enemies.push({x,y,hp:Math.round(b.hp*scale),maxHp:Math.round(b.hp*scale),speed:b.speed,damage:b.damage,xp:b.xp,attack:Math.random(),death:0})}
function target(){let b=null,bd=1e99;for(const e of state.enemies){const d=(e.x-state.player.x)**2+(e.y-state.player.y)**2;if(d<bd){bd=d;b=e}}return b}
function gainXP(n){const p=state.player;p.xp+=n;if(p.xp>=p.xpNeeded){p.xp-=p.xpNeeded;p.level++;p.xpNeeded=Math.floor(p.xpNeeded*1.28);p.maxHp+=18;p.hp=p.maxHp;p.damage+=3;log("LEVEL UP! Nível "+p.level+".")}}
function maybeDrop(){if(Math.random()<.3){const item=structuredClone(GAME_DATA.items[Math.floor(Math.random()*GAME_DATA.items.length)]);state.inventory.unshift(item);if(state.inventory.length>24)state.inventory.pop();log("Loot: "+item.name);const slots={Arma:"weapon",Armadura:"armor",Anel:"ring",Botas:"boots"};const s=slots[item.type];if(s&&!state.equipped[s]){state.equipped[s]=item;log("Equipado: "+item.name)}}}
function chooseMap(id){const m=GAME_DATA.maps.find(a=>a.id===id);if(!m||state.player.level<m.min)return;currentMap=m;state.enemies=[];state.spawnTimer=.15;log("Entrando em "+m.name+".");closeOverlay()}
function openOverlay(panel){document.getElementById("overlay").classList.remove("hidden");document.querySelectorAll(".modal-panel").forEach(p=>p.classList.add("hidden"));document.getElementById(panel).classList.remove("hidden");document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.panel===panel));document.getElementById("modalTitle").textContent=panel==="mapsPanel"?"Mapas":panel==="inventoryPanel"?"Inventário":"Personagem";if(panel==="mapsPanel")drawMapsPanel();if(panel==="inventoryPanel")drawInventory();if(panel==="characterPanel")drawCharacter()}
function closeOverlay(){document.getElementById("overlay").classList.add("hidden")}
function drawMapsPanel(){const e=document.getElementById("mapsPanel");e.innerHTML='<div class="map-grid">'+GAME_DATA.maps.map(m=>{const ok=state.player.level>=m.min;return `<div class="map-card ${ok?"":"locked"}"><h3>${m.name}</h3><p>Níveis ${m.min}–${m.max}</p><p>${ok?"Disponível":"Desbloqueia no nível "+m.min}</p><button class="map-btn" data-map="${m.id}" ${ok?"":"disabled"}>${ok?"Entrar":"Bloqueado"}</button></div>`}).join("")+"</div>";e.querySelectorAll("[data-map]").forEach(b=>b.onclick=()=>chooseMap(b.dataset.map))}
function drawInventory(){const e=document.getElementById("inventoryPanel");e.innerHTML='<div class="inventory-grid">'+Array.from({length:24},(_,i)=>{const it=state.inventory[i];return it?`<div class="item-card"><div class="name">${it.name}</div><div>${it.type}</div><div class="rarity">${it.rarity}</div></div>`:'<div class="item-card"></div>'}).join("")+"</div>"}
function drawCharacter(){const p=state.player;e=document.getElementById("characterPanel");e.innerHTML=`<div class="character-sheet"><div class="hero-preview"><img class="hero-img" src="${pickFrame(ASSETS.warrior_idle,999999)||""}"></div><div class="attr-grid">${[["Vida",Math.round(p.maxHp)],["Dano",p.damage],["Defesa",0],["Vel. Ataque","1.39"],["Crítico","5%"],["Dano Crítico","150%"],["Força",10+p.level],["Destreza",10+p.level],["Inteligência",8],["Vitalidade",10+p.level]].map(([n,v])=>`<div class="attr"><span>${n}</span><b>${v}</b></div>`).join("")}</div></div>`}
function ui(){const p=state.player;document.getElementById("level").textContent=p.level;document.getElementById("mapName").textContent=currentMap.name;document.getElementById("gold").textContent=state.gold;document.getElementById("kills").textContent=state.kills;document.getElementById("hpText").textContent=`${Math.ceil(p.hp)} / ${p.maxHp}`;document.getElementById("xpText").textContent=`${p.xp} / ${p.xpNeeded}`;document.getElementById("hpBar").style.width=p.hp/p.maxHp*100+"%";document.getElementById("xpBar").style.width=p.xp/p.xpNeeded*100+"%";document.getElementById("status").textContent=state.enemies.length?`Farm automático — ${state.enemies.length} esqueletos`:"Procurando inimigos...";const gear=document.getElementById("quickGear"),slots=["weapon","armor","ring","boots"];gear.innerHTML=slots.map(s=>`<div class="gear-slot">${state.equipped[s]?state.equipped[s].name:"Vazio"}</div>`).join("")}
function groundColor(){return currentMap.theme==="forest"?"#54565a":"#424247"}
function drawGround(){ctx.fillStyle=groundColor();ctx.fillRect(0,0,W,H);const tile=ASSETS.ground[0];if(tile){const im=img(tile);for(let y=0;y<H;y+=256)for(let x=0;x<W;x+=256)if(im.complete)ctx.drawImage(im,x,y,256,256)}ctx.fillStyle=currentMap.theme==="forest"?"rgba(64,87,67,.18)":"rgba(20,18,24,.20)";ctx.fillRect(0,0,W,H)}
function draw(){drawGround();for(let i=0;i<10;i++){const px=(i*173+80)%W,py=(i*113+65)%H;const arr=i%2?ASSETS.rocks:ASSETS.mushrooms;const f=arr[Math.floor(i/2)%Math.max(1,arr.length)];if(f){const im=img(f);if(im.complete)ctx.drawImage(im,px-45,py-80,90,90)}}for(const e of state.enemies){ctx.fillStyle="rgba(0,0,0,.25)";ctx.beginPath();ctx.ellipse(e.x,e.y+17,27,9,0,0,Math.PI*2);ctx.fill();const f=pickFrame(ASSETS.skeleton_walk,120);if(f){const im=img(f);if(im.complete)ctx.drawImage(im,e.x-64,e.y-115,128,128)}ctx.fillStyle="#1f242b";ctx.fillRect(e.x-22,e.y-30,44,5);ctx.fillStyle="#e45f63";ctx.fillRect(e.x-22,e.y-30,44*Math.max(0,e.hp/e.maxHp),5)}const p=state.player;ctx.fillStyle="rgba(0,0,0,.25)";ctx.beginPath();ctx.ellipse(p.x,p.y+18,30,10,0,0,Math.PI*2);ctx.fill();const f=pickFrame(ASSETS.warrior_walk,140)||pickFrame(ASSETS.warrior_idle,140);if(f){const im=img(f);if(im.complete)ctx.drawImage(im,p.x-72,p.y-130,144,144)}}
function update(dt){const p=state.player;state.spawnTimer-=dt;state.attackTimer-=dt;if(state.spawnTimer<=0&&state.enemies.length<8){spawnEnemy();state.spawnTimer=.9}const t=target();if(t){const dx=t.x-p.x,dy=t.y-p.y,d=Math.hypot(dx,dy)||1;if(d>70){p.x+=dx/d*110*dt;p.y+=dy/d*110*dt}else if(state.attackTimer<=0){t.hp-=p.damage;state.attackTimer=.75;if(t.hp<=0){state.enemies.splice(state.enemies.indexOf(t),1);state.kills++;state.gold+=currentMap.id==="forest"?5:8;gainXP(t.xp);maybeDrop()}}}for(const e of state.enemies){const dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy)||1;if(d>60){e.x+=dx/d*e.speed*dt;e.y+=dy/d*e.speed*dt}else{e.attack-=dt;if(e.attack<=0){p.hp-=e.damage;e.attack=1.25;if(p.hp<=0){p.hp=p.maxHp;p.x=W/2;p.y=H/2;log("Você morreu e voltou ao centro.")}}}}}
function loop(now){const dt=Math.min(.05,(now-state.last)/1000);state.last=now;update(dt);draw();ui();requestAnimationFrame(loop)}
document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>openOverlay(b.dataset.panel));document.getElementById("closeModal").onclick=closeOverlay;document.getElementById("overlay").onclick=e=>{if(e.target.id==="overlay")closeOverlay()};document.getElementById("resetBtn").onclick=()=>{if(confirm("Apagar o progresso?")){localStorage.removeItem(saveKey);location.reload()}};restore();log("Protótipo V3 iniciado com assets reais do demo.");log("Mapa ativo: "+currentMap.name+".");setInterval(persist,3000);addEventListener("beforeunload",persist);requestAnimationFrame(loop);
