const canvas=document.getElementById("gameCanvas"),ctx=canvas.getContext("2d");
const W=canvas.width,H=canvas.height,saveKey="idle_arpg_v2";
let currentMap=GAME_DATA.maps[0];
const state={player:{x:W/2,y:H/2,hp:100,maxHp:100,damage:10,level:1,xp:0,xpNeeded:100},
gold:0,kills:0,enemies:[],spawnTimer:0,attackTimer:0,inventory:[],equipped:{weapon:null,armor:null,ring:null,boots:null},last:performance.now()};

function log(msg){const el=document.getElementById("log");el.innerHTML="<div>"+msg+"</div>"+el.innerHTML}
function persist(){try{localStorage.setItem(saveKey,JSON.stringify({...state,enemies:[],currentMapId:currentMap.id}))}catch(e){}}
function restore(){try{const raw=localStorage.getItem(saveKey);if(!raw)return;const s=JSON.parse(raw);Object.assign(state,s);Object.assign(state.player,s.player||{});Object.assign(state.equipped,s.equipped||{});currentMap=GAME_DATA.maps.find(m=>m.id===s.currentMapId)||GAME_DATA.maps[0]}catch(e){}}
function spawnEnemy(){const key=currentMap.monsterPool[Math.floor(Math.random()*currentMap.monsterPool.length)],b=GAME_DATA.monsters[key],a=Math.random()*Math.PI*2,d=220+Math.random()*170;let px=state.player.x+Math.cos(a)*d,py=state.player.y+Math.sin(a)*d;px=Math.max(45,Math.min(W-45,px));py=Math.max(65,Math.min(H-45,py));const scale=1+(state.player.level-1)*.06;state.enemies.push({type:key,name:b.name,x:px,y:py,hp:Math.round(b.hp*scale),maxHp:Math.round(b.hp*scale),speed:b.speed,damage:b.damage,xp:b.xp,color:b.color,attack:Math.random()})}
function getTarget(){let best=null,bd=Infinity;for(const e of state.enemies){const d=(e.x-state.player.x)**2+(e.y-state.player.y)**2;if(d<bd){bd=d;best=e}}return best}
function gainXP(n){const p=state.player;p.xp+=n;if(p.xp>=p.xpNeeded){p.xp-=p.xpNeeded;p.level++;p.xpNeeded=Math.floor(p.xpNeeded*1.27);p.maxHp+=18;p.hp=p.maxHp;p.damage+=3;log("LEVEL UP! Agora você é nível "+p.level+".")}}
function maybeDrop(){if(Math.random()<.28){const keys=Object.keys(GAME_DATA.items),k=keys[Math.floor(Math.random()*keys.length)],item=structuredClone(GAME_DATA.items[k]);item.id=k+"-"+Date.now()+"-"+Math.random();state.inventory.unshift(item);if(state.inventory.length>24)state.inventory.pop();log("Loot: "+item.name+".");tryAutoEquip(item)}}
function tryAutoEquip(item){const slots={Arma:"weapon",Armadura:"armor",Anel:"ring",Botas:"boots"},slot=slots[item.type];if(!slot)return;const cur=state.equipped[slot],score=o=>o?Object.values(o.stats||{}).reduce((a,b)=>a+b,0):0;if(!cur||score(item)>score(cur)){state.equipped[slot]=item;log("Equipado: "+item.name+".")}}
function chooseMap(id){const map=GAME_DATA.maps.find(m=>m.id===id);if(!map||state.player.level<map.min)return;currentMap=map;state.enemies=[];state.spawnTimer=.2;log("Você entrou em "+map.name+".");closeOverlay()}
function addMapCards(){const el=document.getElementById("mapsPanel");el.innerHTML='<div class="map-grid">'+GAME_DATA.maps.map(m=>{const ok=state.player.level>=m.min;return `<div class="map-card ${ok?"":"locked"}"><h3>${m.name}</h3><p>Níveis ${m.min}–${m.max}</p><p>${ok?"Disponível":"Desbloqueia no nível "+m.min}</p><button class="map-btn" data-map="${m.id}" ${ok?"":"disabled"}>${ok?"Entrar":"Bloqueado"}</button></div>`}).join("")+"</div>";el.querySelectorAll("[data-map]").forEach(b=>b.onclick=()=>chooseMap(b.dataset.map))}
function addInventory(){const el=document.getElementById("inventoryPanel");el.innerHTML='<div class="inventory-grid">'+Array.from({length:24},(_,i)=>{const item=state.inventory[i];return item?`<div class="item-card"><div class="name">${item.name}</div><div>${item.type}</div><div class="rarity">${item.rarity}</div></div>`:'<div class="item-card"></div>'}).join("")+"</div>"}
function addCharacter(){const p=state.player,attrs=[["Vida",Math.round(p.maxHp)],["Dano",p.damage],["Defesa",0],["Vel. Ataque","1.39"],["Crítico","5%"],["Dano Crítico","150%"],["Força",10+p.level],["Destreza",10+p.level],["Inteligência",8],["Vitalidade",10+p.level]];document.getElementById("characterPanel").innerHTML='<div class="character-sheet"><div class="hero-preview"><div class="hero-circle"></div></div><div class="attr-grid">'+attrs.map(([n,v])=>`<div class="attr"><span>${n}</span><b>${v}</b></div>`).join("")+"</div></div>"}
function openOverlay(panel){document.getElementById("overlay").classList.remove("hidden");document.querySelectorAll(".modal-panel").forEach(p=>p.classList.add("hidden"));document.getElementById(panel).classList.remove("hidden");document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.panel===panel));document.getElementById("modalTitle").textContent=panel==="mapsPanel"?"Mapas":panel==="inventoryPanel"?"Inventário":"Personagem";if(panel==="mapsPanel")addMapCards();if(panel==="inventoryPanel")addInventory();if(panel==="characterPanel")addCharacter()}
function closeOverlay(){document.getElementById("overlay").classList.add("hidden")}
function updateUI(){const p=state.player;document.getElementById("level").textContent=p.level;document.getElementById("mapName").textContent=currentMap.name.replace(" Inicial","");document.getElementById("gold").textContent=state.gold;document.getElementById("kills").textContent=state.kills;document.getElementById("hpText").textContent=`${Math.ceil(p.hp)} / ${p.maxHp}`;document.getElementById("xpText").textContent=`${p.xp} / ${p.xpNeeded}`;document.getElementById("hpBar").style.width=p.hp/p.maxHp*100+"%";document.getElementById("xpBar").style.width=p.xp/p.xpNeeded*100+"%";document.getElementById("status").textContent=state.enemies.length?`Farm automático — ${state.enemies.length} inimigos`:"Procurando inimigos...";const gear=document.getElementById("quickGear"),slots=["weapon","armor","ring","boots"];gear.innerHTML=slots.map(s=>`<div class="gear-slot">${state.equipped[s]?state.equipped[s].name:"Vazio"}</div>`).join("")}
function drawMap(){ctx.clearRect(0,0,W,H);ctx.fillStyle=currentMap.theme==="forest"?"#58745a":"#56515c";ctx.fillRect(0,0,W,H);for(let i=0;i<42;i++){const px=(i*149)%W,py=(i*91)%H;ctx.fillStyle=currentMap.theme==="forest"?"rgba(33,55,39,.35)":"rgba(35,31,42,.28)";ctx.beginPath();ctx.ellipse(px,py,55,27,0,0,Math.PI*2);ctx.fill()}for(let i=0;i<18;i++){const px=(i*71)%W,py=45+((i*127)%(H-70));if(currentMap.theme==="forest"){ctx.fillStyle="#23462f";ctx.beginPath();ctx.ellipse(px,py,26,20,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#6f4d33";ctx.fillRect(px-5,py+12,10,18)}else{ctx.fillStyle="#716979";ctx.fillRect(px-10,py-10,20,32);ctx.fillStyle="#9a92a1";ctx.fillRect(px-14,py-18,28,9)}}}
function draw(){drawMap();for(const e of state.enemies){ctx.fillStyle="rgba(0,0,0,.25)";ctx.beginPath();ctx.ellipse(e.x,e.y+18,22,8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=e.color;ctx.beginPath();ctx.ellipse(e.x,e.y,18,22,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="rgba(255,255,255,.25)";ctx.beginPath();ctx.ellipse(e.x-5,e.y-8,7,10,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#262a31";ctx.fillRect(e.x-20,e.y-32,40,5);ctx.fillStyle="#e25c5c";ctx.fillRect(e.x-20,e.y-32,40*Math.max(0,e.hp/e.maxHp),5)}const p=state.player;ctx.fillStyle="rgba(0,0,0,.26)";ctx.beginPath();ctx.ellipse(p.x,p.y+22,24,9,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#365d9d";ctx.beginPath();ctx.ellipse(p.x,p.y,22,27,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#ead1ba";ctx.beginPath();ctx.arc(p.x,p.y-10,11,0,Math.PI*2);ctx.fill();ctx.fillStyle="#f3d46c";ctx.fillRect(p.x+10,p.y-2,18,5)}
function update(dt){const p=state.player;state.spawnTimer-=dt;state.attackTimer-=dt;if(state.spawnTimer<=0&&state.enemies.length<10){spawnEnemy();state.spawnTimer=.9}const t=getTarget();if(t){const dx=t.x-p.x,dy=t.y-p.y,d=Math.hypot(dx,dy)||1;if(d>54){p.x+=dx/d*118*dt;p.y+=dy/d*118*dt}else if(state.attackTimer<=0){t.hp-=p.damage;state.attackTimer=.72;if(t.hp<=0){state.enemies.splice(state.enemies.indexOf(t),1);state.kills++;state.gold+=currentMap.reward;gainXP(t.xp);maybeDrop()}}}for(const e of state.enemies){const dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy)||1;if(d>50){e.x+=dx/d*e.speed*dt;e.y+=dy/d*e.speed*dt}else{e.attack-=dt;if(e.attack<=0){p.hp-=e.damage;e.attack=1.25;if(p.hp<=0){p.hp=p.maxHp;p.x=W/2;p.y=H/2;log("Você morreu e voltou ao centro.")}}}}}
function loop(now){const dt=Math.min(.05,(now-state.last)/1000);state.last=now;update(dt);draw();updateUI();requestAnimationFrame(loop)}
document.querySelectorAll(".nav-btn").forEach(b=>b.addEventListener("click",()=>openOverlay(b.dataset.panel)));
document.getElementById("closeModal").addEventListener("click",closeOverlay);
document.getElementById("overlay").addEventListener("click",e=>{if(e.target.id==="overlay")closeOverlay()});
document.getElementById("resetBtn").addEventListener("click",()=>{if(confirm("Apagar o progresso deste protótipo?")){localStorage.removeItem(saveKey);location.reload()}});
restore();log("Protótipo v2 iniciado.");log("Mapa ativo: "+currentMap.name+".");requestAnimationFrame(loop);setInterval(persist,3000);addEventListener("beforeunload",persist);
